# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 05:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('familyName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('userType', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
